# Generated by Django 6.0.7 on 2026-08-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã kho')),
                ('name', models.CharField(max_length=200, verbose_name='Tên kho')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Kinh độ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhà kho',
                'verbose_name_plural': 'Nhà kho',
                'db_table': 'warehouse',
            },
        ),
    ]
