# Generated by Django 6.0.7 on 2026-08-13 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_remove_is_active'),
        ('supplier', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu')),
                ('note_type', models.CharField(choices=[('purchase', 'Nhập mua'), ('return', 'Nhập hoàn trả')], default='purchase', max_length=20, verbose_name='Loại phiếu')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã chốt'), ('voided', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nhập')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hủy')),
                ('void_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Người lập')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_notes', to='supplier.supplier', verbose_name='Nhà cung cấp')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_notes_voided', to=settings.AUTH_USER_MODEL, verbose_name='Người hủy')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_notes', to='warehouse.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Phiếu nhập',
                'verbose_name_plural': 'Phiếu nhập',
                'db_table': 'inbound_note',
            },
        ),
        migrations.CreateModel(
            name='InboundNoteLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Đơn giá')),
                ('line_no', models.IntegerField(default=0, verbose_name='Thứ tự dòng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('inbound_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inboundnote', verbose_name='Phiếu nhập')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_lines', to='catalog.material', verbose_name='Vật tư')),
            ],
            options={
                'verbose_name': 'Dòng phiếu nhập',
                'verbose_name_plural': 'Dòng phiếu nhập',
                'db_table': 'inbound_note_line',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Số lượng (+/−)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Đơn giá')),
                ('movement_type', models.CharField(choices=[('inbound_purchase', 'Nhập mua'), ('inbound_return', 'Nhập hoàn trả'), ('outbound_use', 'Xuất sử dụng'), ('transfer_out', 'Điều chuyển đi'), ('transfer_in', 'Điều chuyển đến'), ('stocktake_adjust', 'Điều chỉnh kiểm kê')], max_length=20, verbose_name='Loại biến động')),
                ('date', models.DateField(verbose_name='Ngày nghiệp vụ')),
                ('lot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lô')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ghi sổ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi sổ')),
                ('inbound_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inboundnote', verbose_name='Phiếu nhập nguồn')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.material', verbose_name='Vật tư')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockmovement', verbose_name='Đảo ngược của dòng')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouse.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Dòng sổ kho',
                'verbose_name_plural': 'Dòng sổ kho',
                'db_table': 'stock_movement',
            },
        ),
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['date'], name='ix_inbound_note_date'),
        ),
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['status'], name='ix_inbound_note_status'),
        ),
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['warehouse'], name='ix_inbound_note_warehouse'),
        ),
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['supplier'], name='ix_inbound_note_supplier'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'material', 'date'], name='ix_sm_warehouse_material_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'date'], name='ix_sm_type_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inbound_note'], name='ix_sm_inbound_note'),
        ),
    ]
