# Generated by Django 6.0.7 on 2026-08-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundnote',
            name='note_type',
            field=models.CharField(choices=[('purchase', 'Nhập mua'), ('return_from_site', 'Nhập hàng công trường trả lại')], default='purchase', max_length=20, verbose_name='Loại phiếu'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('inbound_purchase_from_supplier', 'Nhập kho: mua hàng từ nhà cung cấp'), ('inbound_return_from_site', 'Nhập kho: công trường trả lại hàng'), ('outbound_issue_for_use', 'Xuất kho: cấp phát để sử dụng'), ('outbound_transfer_to_warehouse', 'Xuất kho: điều chuyển sang kho khác'), ('inbound_transfer_from_warehouse', 'Nhập kho: điều chuyển từ kho khác'), ('stocktake_adjustment', 'Điều chỉnh tồn: chênh lệch kiểm kê')], max_length=40, verbose_name='Loại biến động'),
        ),
    ]
