# Generated by Django 6.0.7 on 2026-08-18 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_movement_type_choices'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inboundnote',
            name='ix_inbound_note_date',
        ),
        migrations.RemoveIndex(
            model_name='inboundnote',
            name='ix_inbound_note_status',
        ),
        migrations.RemoveIndex(
            model_name='inboundnote',
            name='ix_inbound_note_warehouse',
        ),
        migrations.AlterField(
            model_name='inboundnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người lập'),
        ),
        migrations.AlterField(
            model_name='inboundnote',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='inboundnote',
            name='note_type',
            field=models.CharField(choices=[('purchase', 'Mua hàng từ nhà cung cấp'), ('return_from_site', 'Công trường trả lại hàng')], default='purchase', max_length=20, verbose_name='Loại phiếu'),
        ),
        migrations.AlterField(
            model_name='inboundnote',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_voided', to=settings.AUTH_USER_MODEL, verbose_name='Người hủy'),
        ),
        migrations.AlterField(
            model_name='inboundnote',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_notes', to='warehouse.warehouse', verbose_name='Kho'),
        ),
    ]
