# Generated by Django 6.0.7 on 2026-08-18 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inboundnote_ix_inbound_note_date_and_more'),
        ('supplier', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['date'], name='ix_inboundnote_date'),
        ),
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['status'], name='ix_inboundnote_status'),
        ),
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['warehouse'], name='ix_inboundnote_warehouse'),
        ),
    ]
