# Generated by Django 6.0.7 on 2026-08-20 02:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_is_active'),
        ('inventory', '0005_inboundnote_ix_inboundnote_date_and_more'),
        ('sites', '0001_initial'),
        ('supplier', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã chốt'), ('voided', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nghiệp vụ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hủy')),
                ('void_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('note_type', models.CharField(choices=[('issue_for_use', 'Xuất cấp cho công trường sử dụng'), ('transfer', 'Điều chuyển kho')], default='issue_for_use', max_length=20, verbose_name='Loại phiếu')),
            ],
            options={
                'verbose_name': 'Phiếu xuất',
                'verbose_name_plural': 'Phiếu xuất',
                'db_table': 'outbound_note',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundNoteLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Số lượng')),
                ('line_no', models.IntegerField(default=0, verbose_name='Thứ tự dòng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Dòng phiếu xuất',
                'verbose_name_plural': 'Dòng phiếu xuất',
                'db_table': 'outbound_note_line',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('difference', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Chênh lệch')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('line_no', models.IntegerField(default=0, verbose_name='Thứ tự dòng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Dòng kiểm kê',
                'verbose_name_plural': 'Dòng kiểm kê',
                'db_table': 'stocktake_line',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã chốt'), ('voided', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nghiệp vụ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hủy')),
                ('void_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Phiếu kiểm kê',
                'verbose_name_plural': 'Phiếu kiểm kê',
                'db_table': 'stocktake_note',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inboundnote',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_notes', to='sites.site', verbose_name='Công trường'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='inbound_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inboundnote', verbose_name='Phiếu nhập nguồn'),
        ),
        migrations.AddIndex(
            model_name='inboundnote',
            index=models.Index(fields=['site'], name='ix_inbound_note_site'),
        ),
        migrations.AddField(
            model_name='outboundnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người lập'),
        ),
        migrations.AddField(
            model_name='outboundnote',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_notes', to='sites.site', verbose_name='Công trường'),
        ),
        migrations.AddField(
            model_name='outboundnote',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_to_notes', to='warehouse.warehouse', verbose_name='Kho đích'),
        ),
        migrations.AddField(
            model_name='outboundnote',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_voided', to=settings.AUTH_USER_MODEL, verbose_name='Người hủy'),
        ),
        migrations.AddField(
            model_name='outboundnote',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_notes', to='warehouse.warehouse', verbose_name='Kho'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='outbound_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.outboundnote', verbose_name='Phiếu xuất nguồn'),
        ),
        migrations.AddField(
            model_name='outboundnoteline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_lines', to='catalog.material', verbose_name='Vật tư'),
        ),
        migrations.AddField(
            model_name='outboundnoteline',
            name='outbound_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.outboundnote', verbose_name='Phiếu xuất'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='catalog.material', verbose_name='Vật tư'),
        ),
        migrations.AddField(
            model_name='stocktakenote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người lập'),
        ),
        migrations.AddField(
            model_name='stocktakenote',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_voided', to=settings.AUTH_USER_MODEL, verbose_name='Người hủy'),
        ),
        migrations.AddField(
            model_name='stocktakenote',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_notes', to='warehouse.warehouse', verbose_name='Kho'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='stocktake_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktakenote', verbose_name='Phiếu kiểm kê'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stocktake_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.stocktakenote', verbose_name='Phiếu kiểm kê nguồn'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['outbound_note'], name='ix_sm_outbound_note'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stocktake_note'], name='ix_sm_stocktake_note'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inbound_note__isnull', False), ('outbound_note__isnull', True), ('stocktake_note__isnull', True)), models.Q(('inbound_note__isnull', True), ('outbound_note__isnull', False), ('stocktake_note__isnull', True)), models.Q(('inbound_note__isnull', True), ('outbound_note__isnull', True), ('stocktake_note__isnull', False)), _connector='OR'), name='ck_sm_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'inbound_purchase_from_supplier'), ('unit_price__isnull', False)), models.Q(('unit_price__isnull', True), models.Q(('movement_type', 'inbound_purchase_from_supplier'), _negated=True)), _connector='OR'), name='ck_sm_price_only_purchase'),
        ),
        migrations.AddIndex(
            model_name='outboundnote',
            index=models.Index(fields=['date'], name='ix_outboundnote_date'),
        ),
        migrations.AddIndex(
            model_name='outboundnote',
            index=models.Index(fields=['status'], name='ix_outboundnote_status'),
        ),
        migrations.AddIndex(
            model_name='outboundnote',
            index=models.Index(fields=['warehouse'], name='ix_outboundnote_warehouse'),
        ),
        migrations.AddIndex(
            model_name='outboundnote',
            index=models.Index(fields=['to_warehouse'], name='ix_outbound_note_to_warehouse'),
        ),
        migrations.AddIndex(
            model_name='outboundnote',
            index=models.Index(fields=['site'], name='ix_outbound_note_site'),
        ),
        migrations.AddIndex(
            model_name='stocktakenote',
            index=models.Index(fields=['date'], name='ix_stocktakenote_date'),
        ),
        migrations.AddIndex(
            model_name='stocktakenote',
            index=models.Index(fields=['status'], name='ix_stocktakenote_status'),
        ),
        migrations.AddIndex(
            model_name='stocktakenote',
            index=models.Index(fields=['warehouse'], name='ix_stocktakenote_warehouse'),
        ),
    ]
