# Generated by Django 6.0.7 on 2026-08-06 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã đơn vị')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đơn vị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Đơn vị tính',
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã danh mục')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.materialcategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục vật tư',
                'verbose_name_plural': 'Danh mục vật tư',
                'db_table': 'material_category',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã vật tư')),
                ('name', models.CharField(max_length=300, verbose_name='Tên vật tư')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='catalog.materialcategory', verbose_name='Danh mục')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='catalog.unit', verbose_name='Đơn vị tính')),
            ],
            options={
                'verbose_name': 'Vật tư',
                'verbose_name_plural': 'Vật tư',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Hệ số quy đổi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='catalog.unit', verbose_name='Đơn vị gốc')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='catalog.material', verbose_name='Áp dụng cho vật tư')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='catalog.unit', verbose_name='Đơn vị đích')),
            ],
            options={
                'verbose_name': 'Quy đổi đơn vị',
                'verbose_name_plural': 'Quy đổi đơn vị',
                'db_table': 'unit_conversion',
            },
        ),
        migrations.AddIndex(
            model_name='materialcategory',
            index=models.Index(fields=['parent'], name='material_ca_parent__157083_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category'], name='material_categor_6064ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('from_unit', 'to_unit', 'material'), name='uq_unit_conversion'),
        ),
    ]
