# Generated by Django 6.0.7 on 2026-08-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_materialcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='conversion_type',
            field=models.CharField(choices=[('global', 'Quy đổi toàn cục'), ('material', 'Quy đổi theo vật tư')], default='global', max_length=10, verbose_name='Loại quy đổi'),
        ),
    ]
