# Generated by Django 6.0.7 on 2026-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_unit_conversion_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unitconversion',
            name='uq_unit_conversion',
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(condition=models.Q(('material__isnull', True)), fields=('from_unit', 'to_unit'), name='uq_unit_conversion_global'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('from_unit', 'to_unit', 'material'), name='uq_unit_conversion_material'),
        ),
    ]
