# Generated by Django 6.0.7 on 2026-08-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fix_unit_conversion_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='materialcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='unitconversion',
            name='is_active',
        ),
    ]
