# Generated by Django 6.0.7 on 2026-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã NCC')),
                ('name', models.CharField(max_length=200, verbose_name='Tên NCC')),
                ('tax_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã số thuế')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hợp tác')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'db_table': 'supplier',
            },
        ),
    ]
