# Generated by Django 6.0.7 on 2026-08-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã công trường')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công trường')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='Người phụ trách')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Công trường',
                'verbose_name_plural': 'Công trường',
                'db_table': 'site',
            },
        ),
    ]
