# Generated by Django 6.0.7 on 2026-09-20 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_is_active'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm tất toán'),
        ),
        migrations.AddField(
            model_name='site',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_sites', to=settings.AUTH_USER_MODEL, verbose_name='Người tất toán'),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('completed', 'Đã hoàn thành'), ('inactive', 'Ngừng hoạt động')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='SiteMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Số lượng định mức')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_material_requirements', to='catalog.material', verbose_name='Vật tư')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requirements', to='sites.site', verbose_name='Công trường')),
            ],
            options={
                'verbose_name': 'Định mức vật tư công trường',
                'verbose_name_plural': 'Định mức vật tư công trường',
                'db_table': 'site_material_requirement',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('site', 'material'), name='uq_smr_site_material'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_smr_quantity_positive')],
            },
        ),
    ]
