# Generated by Django 6.0.7 on 2026-09-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_status_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='is_active',
        ),
    ]
